module.exports = {
  automodHandler: require("./automod"),
  commandHandler: require("./command"),
  contextHandler: require("./context"),
  counterHandler: require("./counter"),
  greetingHandler: require("./greeting"),
  inviteHandler: require("./invite"),
  reactionRoleHandler: require("./reactionRoles"),
  statsHandler: require("./stats"),
  translationHandler: require("./translation"),
  afkHandler: require("./afk"),
  chatbotHandler: require("./chatbot"),
  managerHandler: require("./manager"),
  giveawayHandler: require("./giveaway"),
};
